<?php
session_start();require_once __DIR__.'/../../conn.php';require_once __DIR__.'/../../auth.php';requireCustomer();
$r=mysqli_query($conn,"SELECT furniture_id,furniture_name,image,price,stock_quantity FROM Furniture ORDER BY furniture_name ASC");
$ps=array();while($rw=mysqli_fetch_assoc($r))$ps[]=$rw;mysqli_free_result($r);mysqli_close($conn);
$cn=currentUserName();
function imgsrc($p){return '../../image.php?fid='.((int)$p['furniture_id']);}
?><!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Select Product</title><link rel="stylesheet" href="../style.css">
<style>.card-container{background:#fff;padding:40px;border-radius:16px;box-shadow:0 4px 12px rgba(0,0,0,.05);width:100%;max-width:1400px}.search-container{margin-bottom:24px;text-align:center}#productSearch{width:100%;max-width:500px;padding:12px 20px;border-radius:48px;border:1px solid #dadce0;font-size:15px;outline:none;transition:.2s;background:#fff}#productSearch:focus{border-color:#1a73e8;box-shadow:0 0 0 2px rgba(26,115,232,.2)}.product-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:24px;margin-top:16px}.image-link{display:flex;flex-direction:column;text-decoration:none;border-radius:16px;overflow:hidden;background:#fff;border:1px solid #f0f2f5;transition:.25s;position:relative}.image-link:hover{transform:translateY(-6px);box-shadow:0 12px 28px -8px rgba(26,115,232,.25);border-color:rgba(26,115,232,.3)}.image-link.sold-out{opacity:.65;pointer-events:none}.product-img-wrap{position:relative;overflow:hidden;background:#fafafc}.product-img-wrap img{width:100%;aspect-ratio:1/1;object-fit:cover;display:block;transition:transform .35s}.image-link:hover .product-img-wrap img{transform:scale(1.03)}.sold-out-badge{position:absolute;top:12px;right:12px;background:#d93025;color:#fff;padding:4px 12px;border-radius:20px;font-size:.8rem;font-weight:600;display:none}.image-link.sold-out .sold-out-badge{display:block}.product-info{padding:16px;text-align:center}.FurnitureName{font-size:1.1rem;font-weight:600;color:#202124;margin-bottom:6px;display:block}.product-price{font-size:1.05rem;color:#1a73e8;font-weight:500;margin-bottom:4px}.product-stock{font-size:.8rem;color:#5f6368}.product-stock.low{color:#e37400;font-weight:500}.info-label{font-size:.9rem;color:#5f6368;margin-bottom:16px;text-align:center}.user-bar{display:flex;justify-content:space-between;align-items:center;padding:0 0 18px;margin-bottom:20px;border-bottom:1px solid #eef2f6}.user-name{font-weight:500;color:#202124}.user-links a{color:#1a73e8;text-decoration:none;font-size:.9rem;margin-left:16px}.button-back{display:flex;align-items:center;justify-content:center;width:42px;height:42px;position:absolute;top:18px;left:18px;background-color:#1a73e8;color:#fff;text-decoration:none;border-radius:50%;font-size:18px;font-weight:bold;box-shadow:0 2px 5px rgba(0,0,0,.2);transition:.3s;z-index:10}.button-back:hover{background-color:#1557b0;transform:scale(1.1)}#noResultMsg{grid-column:1/-1;text-align:center;padding:40px 20px;color:#5f6368;font-size:1rem}</style></head>
<body><a href="../homepage.php" class="button-back">&#8592;</a><h1>Select Product</h1>
<div class="card-container"><div class="user-bar"><span class="user-name">&#128100; <?php echo htmlspecialchars($cn);?></span><span class="user-links"><a href="../homepage.php">Home</a><a href="../../logout.php">Sign Out</a></span></div>
<div class="search-container"><input type="text" id="productSearch" placeholder="Search furniture name..."></div><p class="info-label">Click on a product to view details and place an order:</p>
<div class="product-grid" id="productGrid">
<?php foreach($ps as $p):$so=((int)$p['stock_quantity']<=0);$low=(!$so&&(int)$p['stock_quantity']<5);?>
<a href="make_orders.php?fid=<?php echo $p['furniture_id'];?>" class="image-link<?php echo $so?' sold-out':'';?>" data-product-name="<?php echo htmlspecialchars(strtolower($p['furniture_name']));?>">
<div class="product-img-wrap"><img src="<?php echo imgsrc($p);?>" alt="<?php echo htmlspecialchars($p['furniture_name']);?>" onerror="this.style.display='none'"><span class="sold-out-badge">Sold Out</span></div>
<div class="product-info"><span class="FurnitureName"><?php echo htmlspecialchars($p['furniture_name']);?></span><div class="product-price">$<?php echo number_format($p['price'],2);?></div><div class="product-stock<?php echo $low?' low':'';?>"><?php echo $so?'Sold Out':'Stock: '.$p['stock_quantity'];?></div></div></a>
<?php endforeach;?></div></div>
<script>(function(){var si=document.getElementById('productSearch');var ls=document.querySelectorAll('#productGrid .image-link');si.addEventListener('input',function(){var t=this.value.trim().toLowerCase();var vc=0;ls.forEach(function(l){var n=l.getAttribute('data-product-name')||'';if(t===''||n.indexOf(t)!==-1){l.style.display='';vc++;}else{l.style.display='none';}});var g=document.getElementById('productGrid');var nm=document.getElementById('noResultMsg');if(vc===0&&t!==''){if(!nm){nm=document.createElement('div');nm.id='noResultMsg';nm.textContent='No furniture found matching \"'+t+'\".';g.appendChild(nm);}else{nm.textContent='No furniture found matching \"'+t+'\".';nm.style.display='';}}else if(nm){nm.style.display='none';}});})();</script></body></html>
