<?php
session_start();require_once __DIR__.'/../../conn.php';require_once __DIR__.'/../../auth.php';requireCustomer();
$cid=currentUserId();$cn=currentUserName();
$cols=array('order_id'=>'Order ID','order_date'=>'Order Date','furniture_id'=>'Furniture ID','order_quantity'=>'Qty','total_amount'=>'Total','delivery_date'=>'Delivery','order_status'=>'Status');
$s1=isset($_GET['sort1'])&&isset($cols[$_GET['sort1']])?$_GET['sort1']:'order_date';
$o1=(isset($_GET['order1'])&&strtoupper($_GET['order1'])==='ASC')?'ASC':'DESC';
$s2=isset($_GET['sort2'])&&isset($cols[$_GET['sort2']])?$_GET['sort2']:'order_id';
$o2=(isset($_GET['order2'])&&strtoupper($_GET['order2'])==='ASC')?'ASC':'DESC';
if($s1===$s2){$s2='order_id';$o2='DESC';}
$sql="SELECT o.order_id,o.order_date,o.furniture_id,f.furniture_name,o.order_quantity,o.total_amount,o.customer_id,o.delivery_date,o.order_status FROM Orders o JOIN Furniture f ON o.furniture_id=f.furniture_id WHERE o.customer_id=? ORDER BY {$s1} {$o1},{$s2} {$o2}";
$st=mysqli_prepare($conn,$sql);mysqli_stmt_bind_param($st,'i',$cid);mysqli_stmt_execute($st);$r=mysqli_stmt_get_result($st);
$ords=array();while($rw=mysqli_fetch_assoc($r))$ords[]=$rw;mysqli_stmt_close($st);mysqli_close($conn);
function sc($s){$s=strtolower($s);if($s==='delivered'||$s==='approved')return'status-delivered';if($s==='open')return'status-processing';if($s==='rejected')return'status-rejected';return'status-pending';}
?><!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>View Orders</title><link rel="stylesheet" href="../style.css">
<style>.page-header{text-align:center;margin-bottom:30px}.page-header h1{font-size:2rem;color:#202124;margin-bottom:8px}.page-header p{color:#5f6368;font-size:1rem}.filter-section{background:#fff;border-radius:24px;padding:20px 24px;margin-bottom:28px;box-shadow:0 1px 2px rgba(0,0,0,.04);border:1px solid #f0f2f5;display:flex;flex-wrap:wrap;align-items:flex-end;gap:16px}.sort-group{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.sort-group select{padding:10px 14px;border-radius:40px;border:1px solid #dadce0;background:#fff;font-size:.9rem;outline:none;transition:.2s}.sort-group select:focus{border-color:#1a73e8;box-shadow:0 0 0 2px rgba(26,115,232,.2)}.sort-label{font-weight:600;color:#1a73e8;font-size:.8rem;text-transform:uppercase;letter-spacing:.3px}.btn-apply{background:#1a73e8;color:#fff;border:none;padding:10px 24px;border-radius:40px;font-size:.9rem;font-weight:500;cursor:pointer;transition:.2s}.btn-apply:hover{background:#1557b0}.btn-delete-link{display:inline-block;background:#fff;color:#d93025;border:1px solid #fce8e6;padding:8px 18px;border-radius:40px;font-size:.85rem;font-weight:500;text-decoration:none;transition:.2s;margin-left:auto}.btn-delete-link:hover{background:#fce8e6}.tbl-wrap{overflow-x:auto;border-radius:20px;background:#fff;box-shadow:0 4px 12px rgba(0,0,0,.05);border:1px solid #f0f2f5}table{width:100%;border-collapse:collapse;font-size:.9rem}th{background:#f8f9fc;padding:16px 14px;font-weight:600;color:#202124;border-bottom:1px solid #e9ecef;white-space:nowrap}td{padding:14px 14px;border-bottom:1px solid #f1f3f4;color:#3c4043}tr:hover{background-color:#fafbfe}.sp{display:inline-block;padding:4px 12px;border-radius:40px;font-size:.75rem;font-weight:500;text-transform:capitalize}.status-delivered{background:#e6f4ea;color:#1e7e34}.status-pending{background:#fef7e0;color:#b45f06}.status-processing{background:#e8f0fe;color:#1a73e8}.status-rejected{background:#fce8e6;color:#c5221f}.empty{text-align:center;padding:48px 20px;color:#5f6368}@media(max-width:768px){.filter-section{flex-direction:column;align-items:stretch}.btn-delete-link{margin-left:0;text-align:center}}</style></head>
<body><a href="../homepage.php" class="button-back">&#8592;</a><div class="card-container"><div class="page-header"><h1>Order Details</h1><p><?php echo htmlspecialchars($cn);?> - Manage your orders</p></div>
<form method="get" action="order.php" class="filter-section">
<div class="sort-group"><span class="sort-label">1st Sort</span><select name="sort1"><?php foreach($cols as $k=>$l):?><option value="<?php echo $k;?>"<?php echo $s1===$k?' selected':'';?>><?php echo $l;?></option><?php endforeach;?></select><select name="order1"><option value="ASC"<?php echo $o1==='ASC'?' selected':'';?>>Ascending</option><option value="DESC"<?php echo $o1==='DESC'?' selected':'';?>>Descending</option></select></div>
<div class="sort-group"><span class="sort-label">2nd Sort</span><select name="sort2"><?php foreach($cols as $k=>$l):?><option value="<?php echo $k;?>"<?php echo $s2===$k?' selected':'';?>><?php echo $l;?></option><?php endforeach;?></select><select name="order2"><option value="ASC"<?php echo $o2==='ASC'?' selected':'';?>>Ascending</option><option value="DESC"<?php echo $o2==='DESC'?' selected':'';?>>Descending</option></select></div>
<button type="submit" class="btn-apply">Apply Sort</button><a href="deleteorder.php" class="btn-delete-link">Delete Orders</a></form>
<div class="tbl-wrap"><?php if(empty($ords)):?><div class="empty">No orders found. <a href="../CreateOrder/selectproduct.php">Place your first order</a></div><?php else:?>
<table><thead><tr><th>Order ID</th><th>Order Date</th><th>Furniture</th><th>Qty</th><th>Total</th><th>Delivery</th><th>Status</th></tr></thead><tbody>
<?php foreach($ords as $o):?><tr><td><strong>#<?php echo $o['order_id'];?></strong></td><td><?php echo htmlspecialchars($o['order_date']);?></td><td><?php echo htmlspecialchars($o['furniture_name']);?> (#<?php echo $o['furniture_id'];?>)</td><td><?php echo $o['order_quantity'];?></td><td>$<?php echo number_format($o['total_amount'],2);?></td><td><?php echo htmlspecialchars($o['delivery_date']);?></td><td><span class="sp <?php echo sc($o['order_status']);?>"><?php echo htmlspecialchars($o['order_status']);?></span></td></tr><?php endforeach;?></tbody></table><?php endif;?></div></div></body></html>
