<?php session_start();require_once __DIR__.'/../conn.php';require_once __DIR__.'/../auth.php';requireStaff();
$sn=currentUserName();$si=currentUserId();
$to=mysqli_fetch_row(mysqli_query($conn,"SELECT COUNT(*) FROM Orders"))[0];
$tf=mysqli_fetch_row(mysqli_query($conn,"SELECT COUNT(*) FROM Furniture"))[0];
$lm=mysqli_fetch_row(mysqli_query($conn,"SELECT COUNT(*) FROM Material WHERE physical_quantity<50"))[0];
$pt=mysqli_fetch_row(mysqli_query($conn,"SELECT COUNT(*) FROM Orders WHERE order_status='Open'"))[0];
$rr=mysqli_query($conn,"SELECT o.order_id,c.customer_name,o.total_amount,o.order_status FROM Orders o JOIN Customer c ON o.customer_id=c.customer_id ORDER BY o.order_date DESC LIMIT 5");
$ros=array();while($rw=mysqli_fetch_assoc($rr))$ros[]=$rw;mysqli_free_result($rr);mysqli_close($conn);
?><!DOCTYPE html><html><head><meta charset="UTF-8"><title>Dashboard</title><link rel="stylesheet" href="style.css">
<style>*{margin:0;padding:0;box-sizing:border-box;font-family:Roboto,sans-serif}body{background:#f5f5f5;display:flex;height:100vh;overflow:hidden}.mc{flex:1;display:flex;flex-direction:column;overflow-y:auto}.tb{background:#fff;padding:12px 32px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #e0e0e0;position:sticky;top:0;z-index:5}.pt{font-size:22px;font-weight:500;color:#202124}.ui{display:flex;align-items:center;gap:16px}.av{width:40px;height:40px;background:#1a73e8;border-radius:50%;display:flex;align-items:center;justify-content:center;color:#fff;font-weight:500}.cc{padding:24px 32px}.sg{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:20px;margin-bottom:32px}.sc{background:#fff;border-radius:16px;padding:20px;box-shadow:0 1px 2px rgba(0,0,0,.05)}.sn{font-size:32px;font-weight:500;color:#1a73e8;margin-bottom:8px}.sl{font-size:14px;color:#5f6368}.qa{background:#fff;border-radius:16px;padding:20px;margin-bottom:32px;box-shadow:0 1px 2px rgba(0,0,0,.05)}.st{font-size:18px;font-weight:500;margin-bottom:16px;color:#202124}.bg{display:flex;flex-wrap:wrap;gap:12px}.btn{background:#f8f9fa;border:1px solid #dadce0;padding:8px 20px;border-radius:24px;font-size:14px;font-weight:500;color:#1a73e8;cursor:pointer;text-decoration:none;display:inline-block;transition:.2s}.bp{background:#1a73e8;border-color:#1a73e8;color:#fff}.bp:hover{background:#1557b0}.btn:hover{background:#e8e8e8}.ro{background:#fff;border-radius:16px;padding:20px;box-shadow:0 1px 2px rgba(0,0,0,.05);overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:12px 8px;border-bottom:1px solid #e0e0e0}th{font-weight:500;color:#5f6368;font-size:13px}.sb{display:inline-block;padding:4px 10px;border-radius:16px;font-size:12px;font-weight:500}.sbo{background:#e8f0fe;color:#1a73e8}.sba{background:#e6f4ea;color:#137333}.sbr{background:#fce8e6;color:#c5221f}</style></head>
<body><div id="sidebar-container"></div><div class="mc"><div class="tb"><div class="pt">Dashboard</div><div class="ui"><span><?php echo htmlspecialchars($sn);?> (SID:<?php echo $si;?>)</span><div class="av"><?php echo htmlspecialchars(substr($sn,0,1));?></div></div></div>
<div class="cc"><div class="sg"><div class="sc"><div class="sn"><?php echo $to;?></div><div class="sl">Total Orders</div></div><div class="sc"><div class="sn"><?php echo $tf;?></div><div class="sl">Furniture Types</div></div><div class="sc"><div class="sn"><?php echo $lm;?></div><div class="sl">Low Stock Mats</div></div><div class="sc"><div class="sn"><?php echo $pt;?></div><div class="sl">Pending</div></div></div>
<div class="qa"><div class="st">Quick Actions</div><div class="bg"><a class="btn bp" href="Create/createFurniture.php">+ New Furniture</a><a class="btn bp" href="Create/createMaterial.php">+ New Material</a><a class="btn" href="View/viewMaterials.php">Material Stock</a><a class="btn" href="reports.php">Reports</a></div></div>
<div class="ro"><div class="st">Recent 5 Orders</div><table><thead><tr><th>ID</th><th>Customer</th><th>Total</th><th>Status</th></tr></thead><tbody>
<?php foreach($ros as $o):?><tr><td>#<?php echo $o['order_id'];?></td><td><?php echo htmlspecialchars($o['customer_name']);?></td><td>$<?php echo number_format($o['total_amount'],2);?></td><td><span class="sb sb<?php echo substr(strtolower($o['order_status']),0,1);?>"><?php echo htmlspecialchars($o['order_status']);?></span></td></tr><?php endforeach;?>
<?php if(empty($ros)):?><tr><td colspan="4" style="text-align:center;color:#5f6368;">No orders yet.</td></tr><?php endif;?></tbody></table></div></div></div>
<script src="sidebar.js"></script><script>loadSidebar('dashboard');</script></body></html>
