<?php session_start();require_once __DIR__."/../conn.php";require_once __DIR__."/../auth.php";require_once __DIR__."/../sort_utils.php";requireStaff();
$allowed=['f.furniture_name'=>'Furniture','f.price'=>'Price','oc'=>'Orders','tq'=>'Qty Sold','ts'=>'Total Sales'];list($sort,$order)=get_sort_params($allowed,'ts');
$sql="SELECT f.furniture_id,f.furniture_name,f.price,COUNT(o.order_id) as oc,COALESCE(SUM(o.order_quantity),0) as tq,COALESCE(SUM(o.total_amount),0) as ts FROM Furniture f LEFT JOIN Orders o ON f.furniture_id=o.furniture_id GROUP BY f.furniture_id ".sort_clause($sort,$order);
$r=mysqli_query($conn,$sql);$rep=array();while($rw=mysqli_fetch_assoc($r))$rep[]=$rw;mysqli_free_result($r);
$gt=mysqli_fetch_row(mysqli_query($conn,"SELECT COALESCE(SUM(total_amount),0) FROM Orders"))[0];
$to=mysqli_fetch_row(mysqli_query($conn,"SELECT COUNT(*) FROM Orders"))[0];
$tq=mysqli_fetch_row(mysqli_query($conn,"SELECT COALESCE(SUM(order_quantity),0) FROM Orders"))[0];mysqli_close($conn);
?><!DOCTYPE html><html><head><meta charset="UTF-8"><title>Reports</title><link rel="stylesheet" href="style.css">
<style>.mc{padding:24px 32px}.sum{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:24px}.sc{background:#fff;border-radius:16px;padding:20px;text-align:center;box-shadow:0 1px 2px rgba(0,0,0,.05)}.sn{font-size:28px;font-weight:500;color:#1a73e8}.sl{font-size:13px;color:#5f6368;margin-top:4px}.tw{background:#fff;border-radius:20px;padding:20px;overflow-x:auto;box-shadow:0 1px 3px rgba(0,0,0,.06)}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{padding:12px 14px;border-bottom:1px solid #e0e0e0;text-align:center}th{font-weight:500;color:#5f6368;font-size:13px}.thumb{width:48px;height:48px;border-radius:8px;object-fit:cover;border:1px solid #eee}</style></head>
<body><div id="sidebar-container"></div><div class="mc"><div class="top-bar"><div class="page-title">Reports Center</div></div><div style="padding:24px 32px">
<div class="sum"><div class="sc"><div class="sn"><?php echo $to;?></div><div class="sl">Total Orders</div></div><div class="sc"><div class="sn"><?php echo $tq;?></div><div class="sl">Items Sold</div></div><div class="sc"><div class="sn">$<?php echo number_format($gt,2);?></div><div class="sl">Total Revenue</div></div></div>
<h2 style="margin:24px 0 16px;font-weight:500;">Sales by Furniture</h2>
<div class="tw"><table><thead><tr><th><?php echo sortable_th('f.furniture_name','Furniture',$sort,$order);?></th><th><?php echo sortable_th('f.price','Price',$sort,$order);?></th><th><?php echo sortable_th('oc','Orders',$sort,$order);?></th><th><?php echo sortable_th('tq','Qty Sold',$sort,$order);?></th><th><?php echo sortable_th('ts','Total Sales',$sort,$order);?></th></tr></thead><tbody>
<?php foreach($rep as $rw):?><tr><td><strong><?php echo htmlspecialchars($rw["furniture_name"]);?></strong></td><td>$<?php echo number_format($rw["price"],2);?></td><td><?php echo $rw["oc"]?:0;?></td><td><?php echo $rw["tq"]?:0;?></td><td><strong><?php echo $rw["ts"]?"$".number_format($rw["ts"],2):"-";?></strong></td></tr><?php endforeach;?></tbody></table></div></div></div>
<script src="sidebar.js"></script><script>loadSidebar("reports");</script></body></html>